#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 17:20:23 2017

@author: root
"""
import tkinter

root = tkinter.Tk()
def key(event):
    print ("pressed", repr(event.char))
frame = tkinter.Frame(root, width=100, height=100)
frame.bind("<Key>", key)
frame.pack()

root.mainloop()



'''
Output:
	'''